import './globals.css';
import Sidebar from '../components/Sidebar';

export const metadata = {
  title: 'ChatGPT Generator',
  description: 'Generated by Mahsa',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body style={{ display: 'flex', margin: 0 }}>
        <Sidebar />
        <main style={{ flex: 1, padding: '20px' }}>
          {children}
        </main>
      </body>
    </html>
  );
}
